name: Daily XRP Blacklist Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 UTC every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-blacklist:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper git operations
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xrpl-py python-dotenv requests
        
    - name: Verify environment
      run: |
        if [ -z "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
          echo "::error::DISCORD_WEBHOOK_URL secret is not set"
          exit 1
        fi
        echo "Discord webhook URL is configured"
        
    - name: Create .env file
      run: |
        echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" > .env
        
    - name: Initialize blacklist file
      run: |
        if [ ! -f "blacklisted_addresses.json" ]; then
          echo "[]" > blacklisted_addresses.json
          echo "Created new blacklisted_addresses.json file"
        fi
      
    - name: Run blacklist checker
      run: |
        echo "Starting blacklist checker..."
        python3 -u xrp_blacklist_tracker.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      
    - name: Upload blacklisted addresses
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blacklisted-addresses
        path: blacklisted_addresses.json
        retention-days: 90
        
    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet blacklisted_addresses.json || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add blacklisted_addresses.json
        git commit -m "Update blacklisted addresses [skip ci]"
        git push 